### ISSUE TITLE
Compile error when using `narrate::{bail, error_from}` without specifying `anyhow` as dependency

### ISSUE THREAD

**Issue by kaplanz** [sonro/narrate#17]
# Bug Report

Using `narrate::{bail, error_from}` in a project that doesn't specify `anyhow` as a dependency separately (regardless of if the `anyhow` feature of `narrate` is used) unconditionally triggers a compile error. (AFAIK this is a bug, as documentation doesn't specify that `anyhow` must also be a dependency.)

### `Cargo.toml`
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
narrate = { version = "0.4.1", features = ["anyhow"] }
# The above line could also have simply been:
# narrate = "0.4.1"
```

### `src/main.rs`

```rust
fn main() -> narrate::Result<()> {
    narrate::bail!("this should compile");
}
```

### `cargo build`

See the triggered compiler error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `anyhow`
 --> src/main.rs:2:5
  |
2 |     narrate::bail!("this should compile");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `anyhow`
  |
  = note: this error originates in the macro `$crate::error_from` which comes from the expansion of the macro `narrate::bail` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `main` (bin "main") due to previous error
```

## Cause

It seems that this issue stems from `narrate` not unconditionally requiring `anyhow` as a  _non-optional_ dependency. My best guess is that this was introduced in bdba927. This seems related to #4.

## Remedy

In the meantime while awaiting a fix, adding `anyhow` as a dependency in `Cargo.toml` prevents the compile error.

## Notes

Otherwise, `narrate` is a great library that does exactly what I was looking for!

**Comment by sonro** [comment]
Thank you for the very well written bug report.

Dreadfully sorry for the delay, I have found the source of the bug and will release a new version today.

**Comment by sonro** [comment]
Latest [release](https://github.com/sonro/narrate/releases/tag/v0.4.2) now on [crates.io](https://crates.io/crates/narrate) fixes this bug.
